# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Personal Magazine
tagline:          A place to keep what I learn
url:              http://getpoole.com
paginate:         1
baseurl:          http://darcamo.github.io/
author:
  name:           Darlan Cavalcante Moreira
  url:            https://plus.google.com/+DarlanCavalcanteMoreira/
  email:          darcamo@gmail.com

# Custom vars
version:          1.0.0
github:           https://github.com/darcamo
repo:             https://github.com/darcamo/darcamo.github.com

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
